# Generated by Django 2.1.3 on 2019-05-02 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('age_range', models.SmallIntegerField(null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=32, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=32, verbose_name='Longitude')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_app.MeetingType'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting_app.Place'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matching',
            name='female',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female', to='meeting_app.MeetingRequest'),
        ),
        migrations.AddField(
            model_name='matching',
            name='male',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male', to='meeting_app.MeetingRequest'),
        ),
    ]
