# Generated by Django 2.1.3 on 2019-05-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190520_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_id',
        ),
    ]
