# Generated by Django 2.2 on 2019-05-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_user_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nickname',
        ),
    ]
