# Generated by Django 2.1.3 on 2019-05-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_remove_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='name',
        ),
    ]
