# Generated by Django 2.1.3 on 2019-05-16 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='party',
            name='image',
        ),
        migrations.AlterField(
            model_name='partycomment',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_comments', to='party_app.Party'),
        ),
        migrations.AddField(
            model_name='partyimage',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_image', to='party_app.Party'),
        ),
    ]
